/**
 * tools/site.js — builds the GitHub Pages site into ./site
 *   site/index.html  = landing page (what visitors see first)
 *   site/play.html   = the playable app (same self-contained file)
 *   site/og.png      = social preview image
 * The dashboard stays ONE self-contained file: play.html is a byte-for-byte
 * copy of beast-chess.html, so nothing here can break the offline promise.
 */
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const SITE = path.join(ROOT, 'site');

const app = fs.readFileSync(path.join(ROOT, 'beast-chess.html'), 'utf8');
fs.rmSync(SITE, { recursive: true, force: true });
fs.mkdirSync(SITE, { recursive: true });
fs.writeFileSync(path.join(SITE, 'play.html'), app);
fs.copyFileSync(path.join(ROOT, 'og.png'), path.join(SITE, 'og.png'));
fs.writeFileSync(path.join(SITE, 'README.md'), [
  '# Beast Chess — web build',
  '',
  'This folder is generated by `node tools/site.js` and published to GitHub Pages.',
  '',
  '- `index.html` — landing page (hand-written in `site-src/index.html`)',
  '- `play.html` — the training dashboard, a byte-for-byte copy of `beast-chess.html`',
  '- `og.png` — social preview image',
  ''
].join('\n'));

const ico = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%230b0f16'/%3E%3Cg fill='none' stroke='%23ffc400' stroke-width='2.1' stroke-linecap='round' stroke-linejoin='round'%3E%3Ccircle cx='16' cy='10' r='3.1'/%3E%3Cpath d='M14.1 13.1c-.6 2.4-1.8 4.2-2.8 5.9h9.4c-1-1.7-2.2-3.5-2.8-5.9'/%3E%3Cpath d='M10 25.5h12'/%3E%3Cpath d='M11.6 19 9.8 25.5M20.4 19l1.8 6.5'/%3E%3C/g%3E%3C/svg%3E";
let landing = fs.readFileSync(path.join(ROOT, 'site-src', 'index.html'), 'utf8');
landing = landing.replace(/__FAVICON__/g, ico).replace(/__OG__/g, 'og.png');
fs.writeFileSync(path.join(SITE, 'index.html'), landing);
console.log('site built: index.html (landing) + play.html (' + Math.round(app.length / 1024) + ' KB) + og.png');
